package oasis.vend.manage.domain;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import oasis.vend.common.annotation.Excel;
import oasis.vend.common.core.domain.BaseEntity;

/**
 * Order table对象 order
 * 
 * @author oasis
 * @date 2025-01-20
 */
public class Order extends BaseEntity
{
    private static final long serialVersionUID = 1L;

    /** ID */
    private Long id;

    /** Order code (date + seq.) */
    @Excel(name = "Order code (date + seq.)")
    private String code;

    /** Status */
    @Excel(name = "Status")
    private Long status;

    /** Auto-generated (1/0) */
    @Excel(name = "Auto-generated (1/0)")
    private Long isAutoGenerated;

    /** VM inner code */
    @Excel(name = "VM inner code")
    private String vmInnerCode;

    /** User ID */
    @Excel(name = "User ID")
    private Long userId;

    /** Region ID */
    private Long regionId;

    /** Description */
    private String desc;

    /** Order type */
    @Excel(name = "Order type")
    private Long type;

    /** Assignor ID */
    private Long assignorId;

    public void setId(Long id) 
    {
        this.id = id;
    }

    public Long getId() 
    {
        return id;
    }
    public void setCode(String code) 
    {
        this.code = code;
    }

    public String getCode() 
    {
        return code;
    }
    public void setStatus(Long status) 
    {
        this.status = status;
    }

    public Long getStatus() 
    {
        return status;
    }
    public void setIsAutoGenerated(Long isAutoGenerated) 
    {
        this.isAutoGenerated = isAutoGenerated;
    }

    public Long getIsAutoGenerated() 
    {
        return isAutoGenerated;
    }
    public void setVmInnerCode(String vmInnerCode) 
    {
        this.vmInnerCode = vmInnerCode;
    }

    public String getVmInnerCode() 
    {
        return vmInnerCode;
    }
    public void setUserId(Long userId) 
    {
        this.userId = userId;
    }

    public Long getUserId() 
    {
        return userId;
    }
    public void setRegionId(Long regionId) 
    {
        this.regionId = regionId;
    }

    public Long getRegionId() 
    {
        return regionId;
    }
    public void setDesc(String desc) 
    {
        this.desc = desc;
    }

    public String getDesc()
    {
        return desc;
    }
    public void setType(Long type)
    {
        this.type = type;
    }

    public Long getType()
    {
        return type;
    }
    public void setAssignorId(Long assignorId) 
    {
        this.assignorId = assignorId;
    }

    public Long getAssignorId() 
    {
        return assignorId;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
            .append("id", getId())
            .append("code", getCode())
            .append("status", getStatus())
            .append("isAutoGenerated", getIsAutoGenerated())
            .append("vmInnerCode", getVmInnerCode())
            .append("userId", getUserId())
            .append("regionId", getRegionId())
            .append("desc", getDesc())
            .append("type", getType())
            .append("assignorId", getAssignorId())
            .append("createTime", getCreateTime())
            .append("updateTime", getUpdateTime())
            .toString();
    }
}
